#!/bin/bash
crictl pull docker.io/calico/apiserver:v3.26.1
crictl pull docker.io/calico/cni:v3.26.1
crictl pull docker.io/calico/csi:v3.26.1
crictl pull docker.io/calico/kube-controllers:v3.26.1
crictl pull docker.io/calico/node-driver-registrar:v3.26.1
crictl pull docker.io/calico/node:v3.26.1
crictl pull docker.io/calico/pod2daemon-flexvol:v3.26.1
crictl pull docker.io/calico/typha:v3.26.1
crictl pull ghcr.io/k8snetworkplumbingwg/ib-sriov-cni:v1.0.3
crictl pull ghcr.io/k8snetworkplumbingwg/network-resources-injector:v1.4
crictl pull ghcr.io/k8snetworkplumbingwg/sriov-cni:v2.7.0
crictl pull ghcr.io/k8snetworkplumbingwg/sriov-network-device-plugin:v3.5.1
crictl pull ghcr.io/k8snetworkplumbingwg/sriov-network-operator-webhook:v1.1.0
crictl pull nvcr.io/nvidia/mellanox/sriov-network-operator-config-daemon:network-operator-23.5.0
crictl pull nvcr.io/nvidia/mellanox/sriov-network-operator:network-operator-23.5.0
crictl pull quay.io/tigera/operator:v1.30.4
crictl pull registry.k8s.io/coredns/coredns:v1.10.1
crictl pull registry.k8s.io/etcd:3.5.7-0
crictl pull registry.k8s.io/kube-apiserver:v1.27.4
crictl pull registry.k8s.io/kube-controller-manager:v1.27.4
crictl pull registry.k8s.io/kube-proxy:v1.27.4
crictl pull registry.k8s.io/kube-scheduler:v1.27.4
crictl pull registry.k8s.io/pause:3.6
crictl pull registry.k8s.io/pause:3.9
